# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hackertea < Formula
  desc ""
  homepage "https://github.com/KarolosLykos/hackertea"
  version "0.0.6"

  on_macos do
    url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.6/hackertea_0.0.6_darwin_all.tar.gz"
    sha256 "f8204bb23c11e866e97ed6224a71abc4705caa7b8f0e189f8b675c4ba7f2f5f7"

    def install
      bin.install "hackertea"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.6/hackertea_0.0.6_linux_arm64.tar.gz"
      sha256 "b4ab40c3aacad6ac3632d13acfe216cbbc6f9c91fb72276d73c38265c0a0b3dc"

      def install
        bin.install "hackertea"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.6/hackertea_0.0.6_linux_amd64.tar.gz"
      sha256 "bce3e165542cdeeae7f8abc8c3b83476d42a6cdec3ecb4175d2219097c2052bf"

      def install
        bin.install "hackertea"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.6/hackertea_0.0.6_linux_armv6.tar.gz"
      sha256 "9999a5767340738f200fa3e165290d286e4335faa198e34b09c49f567eaf53f2"

      def install
        bin.install "hackertea"
      end
    end
  end
end
