# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hackertea < Formula
  desc ""
  homepage "https://github.com/KarolosLykos/hackertea"
  version "0.0.8"

  on_macos do
    url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.8/hackertea_0.0.8_darwin_all.tar.gz"
    sha256 "e73965541f76eb0ed9c0c6505a86c8783b71096d35f68ded1e861cd369295220"

    def install
      bin.install "hackertea"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.8/hackertea_0.0.8_linux_armv6.tar.gz"
      sha256 "e4b7f8fff852d5e3e9f3a7aaf22fcb9910d19f399995eca92e27f37886c10d9a"

      def install
        bin.install "hackertea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.8/hackertea_0.0.8_linux_arm64.tar.gz"
      sha256 "f8360215d4e3b82efea9d9ef9af3653bf6f5e77810edaa39dca4133446fe1a72"

      def install
        bin.install "hackertea"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KarolosLykos/hackertea/releases/download/v0.0.8/hackertea_0.0.8_linux_amd64.tar.gz"
      sha256 "33d2f073b128d98263e58af835cc1646b289e433642a014b499aa491e594ed2d"

      def install
        bin.install "hackertea"
      end
    end
  end
end
